### ISSUE TITLE
String with quotes and , during binding

### ISSUE THREAD

**Issue by semoac** [Shopify/krane#523]
# Bug report

When binding variables to a string with `,`, kubernetes-deploy parser thinks is a different binding.

**Expected behavior:**  When using quotes during the binding definition with a string containing `,`, kubernetes-deploy should capture the entire string.

**Actual behavior:**  When using quotes during the binding definition with a string containing `,`, kubernetes-deploy thinks is another variable.

**Version(s) affected:** `v0.26.7`

### Steps to Reproduce

Ex: This ERB file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-celery-config
data:
  GIT_HASH: "<%= current_sha %>"
  QUEUES: "<%= queues %>"
```

When using `REVISION=1 kubernetes-deploy --template-dir=app2/ --bindings=queues='a,b' queues dev.k8s.local`, becomes:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-celery-config
data:
  GIT_HASH: "1"
  QUEUES: a
```

`QUEUES` is set to `a` instead of  `a,b`
