### ISSUE TITLE
Persistent volume should be a priority resource

### ISSUE THREAD

**Issue by dalehamel** [Shopify/krane#629]
# Bug report

PersistentVolumeClaim is a priority resource, but PersistentVolume is not.

I suspect we at shopify haven't hit this because we use a dynamic provisioner. If, however, you manually must create a persistent volume before you can claim it, I think it makes sense that the persistentvolume itself be at least as high of a priority (if not higher) as the claim for the volume.

**Version(s) affected:** all (afaict)

### Steps to Reproduce

Create a filestore NFS instance https://cloud.google.com/filestore/

Use a template as the following, but set the IP to the address provided when the above is provisioned:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: some-pv
spec:
  capacity:
    storage: 1G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfs_store
    server: 10.145.170.90

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: some-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1G
```

When you deploy this template with kubernetes-deploy, it will timeout as the claim cannot be satisfied

**Proposal:** Add persistent volume to the list of priority resources, and an associated unit test to verify that a manually created claim and volume can proceed (i suspect this would currently fail)
