### ISSUE TITLE
Krane failing with the latest ubuntu version on github actions

### ISSUE THREAD

**Issue by opsidao** [Shopify/krane#850]
# Bug report

In the latest [version of the ubuntu image used for Github actions](https://github.com/actions/virtual-environments/blob/ubuntu20/20211209.3/images/linux/Ubuntu2004-README.md), they updated kubectl to version 1.23.0.

According to the [Kuberentes Changelog for this version](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md) they have:

> Removed kubectl --dry-run empty default value and boolean values. kubectl --dry-run usage must be specified with --dry-run=(server|client|none). (#105327, @julianvmodesto)

This breaks Krane on version 2.1.5, but from what I can see in the Krane's changelog this hasn't been addressed yet. Sorry if this has actually been fixed in a more recent version of Krane, don't really have the time to test it (holidays starting in 5 minutes 👼).

The error that this generates is:

```
[FATAL][2021-12-15 16:30:06 +0000]	Invalid template: ConfigMap-application20211215-6158-o5fuyo.yml
[FATAL][2021-12-15 16:30:06 +0000]	> Error message:
[FATAL][2021-12-15 16:30:06 +0000]	    error: --dry-run flag without a value was specified. A value must be set: "none", "server", or "client".
```

### Steps to Reproduce

1. Setup AWS credentials in your workflow:
```yaml
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
```
2. Set your kubeconfig with:
```yaml
- name: Setup kubeconfig
  run: |
    aws eks update-kubeconfig --name $CLUSTER_NAME --alias $CLUSTER_NAME
```
3. Installl krane within a Github workflow with a step similar to this:
```yaml
- name: Install krane
   run: |
     gem install krane -v 2.1.5
```
4. Try to run a deploy the usual way

# Workaround

For now, we have found a workaround by installing the previous version of kubectl and overriding the one installed by default with a step like this:

```yaml
- name: Install kubectl 1.22.4
  run: |
    sudo apt remove -y kubectl
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl
    sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    sudo apt-get update
    sudo apt install kubectl=1.22.4-00
    sudo cp /usr/bin/kubectl /usr/local/bin/kubectl
```
